Repository Resaqulyubi/covid-19-api-cron-test-main, pull requests merged in 2020-10, with the labels that each got.

#1 Update main.yml
  .github/workflows/main.yml
Labels: hacktoberfest-accepted

#2 Update main.yml
  .github/workflows/main.yml
Labels: invalid

#3 Update main.yml
  .github/workflows/main.yml
Labels: bug
